---
- name: Remove default nvm lines - Debian
  lineinfile:
    path: '{{ nvm_profile }}'
    regexp: 'NVM_DIR'
    state: absent
  when:
    - nvm_installation is succeeded
    - nvm_installation.changed

- name: Add lines to load nvm before capistrano condition - Debian
  blockinfile:
    path: '{{ nvm_profile }}'
    insertbefore: "# If not running interactively, don't do anything"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  when:
    - nvm_installation is succeeded
    - nvm_installation.changed
