- import_tasks: redhat/remove.yml
  when: ansible_facts["os_family"] | default(os_family) == "RedHat"

- import_tasks: debian/remove.yml
  when: ansible_facts["os_family"] | default(os_family) == "Debian"
