- name: Upgrade all packages - Redhat
  yum:
    name: '*'
    state: latest

- name: Install epel-release - Redhat
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install required packages - Redhat
  yum:
    name: '{{ default_required_packages + ["@Development tools"] + custom_packages | default([]) }}'
    update_cache: yes
    state: present
